# Generated by Django 6.0.6 on 2026-06-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('ring', 'Ring'), ('pendant', 'Pendant'), ('nosepin', 'Nosepin'), ('necklace', 'Necklace'), ('earring', 'Earrings'), ('chain', 'Chain'), ('bracelet', 'Bracelet'), ('bangle', 'Bangle')], default='ring', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_sku', models.CharField(max_length=100, unique=True)),
                ('metal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('diamond_color', models.CharField(blank=True, max_length=20, null=True)),
                ('diamond_clarity', models.CharField(blank=True, max_length=20, null=True)),
                ('carat_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('size_or_length', models.CharField(blank=True, help_text='e.g., Ring Size 6, 18-inch chain, 2.4 bangle', max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
