# Generated by Django 6.0.6 on 2026-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
