# Generated by Django 6.0.6 on 2026-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='carat_weight',
            field=models.CharField(blank=True, help_text="e.g., '0.50', '0.75 TCW', or '0.50 Center / 0.25 Accents'", max_length=100, null=True),
        ),
    ]
