# Generated by Django 6.0.6 on 2026-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_carat_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='diamond_clarity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diamond_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_or_length',
            field=models.CharField(blank=True, help_text='e.g., Ring Size 6, 18-inch chain, 2.4 bangle', max_length=100, null=True),
        ),
    ]
