# Generated by Django 6.0.6 on 2026-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_diamond_clarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='diamond_pcs',
            field=models.CharField(blank=True, help_text="Number of diamond pieces (e.g., '14', '42 Center & Accents')", max_length=100, null=True),
        ),
    ]
