# Generated by Django 6.0.6 on 2026-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_diamond_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='gross_weight',
            field=models.CharField(blank=True, help_text="e.g., '5.24g' or '12.5 Grams'", max_length=100, null=True),
        ),
    ]
