# Generated by Django 6.0.6 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='status',
            field=models.CharField(default='cart', max_length=15),
        ),
    ]
