# Generated by Django 6.0.6 on 2026-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_cart_item_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='carat_weight',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='metal_type',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_metal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='diamond_carat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='diamond_charges',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='diamond_charges_discount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='diamond_cut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='making_charges',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='making_charges_discount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='metal_charges',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='metal_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diamond_pcs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_or_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
