# Generated by Django 6.0.6 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productvariant_carat_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_link',
        ),
        migrations.AddField(
            model_name='product',
            name='image_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
